#!/bin/bash

# Detect linux distro
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
else
    OS=$(uname -s)
fi

print_wpa="Installing wpa_supplicant\n"
print_dhcp="Installing dhclient\n"

# Call respective package managers
if [ "$OS" == "ubuntu" ] || [ "$OS" == "debian" ] || [ "$OS" == "mint" ]; then
	if ! dpkg -s wpa_supplicant >/dev/null 2>&1; then
		printf "$print_wpa"
		sudo apt install wpa_supplicant -y
	fi
	if ! dpkg -s dhclient >/dev/null 2>&1; then
		printf "$print_dhcp"
		sudo apt install dhclient -y
	fi
elif [ "$OS" == "manjaro" ] || [ "$OS"=="arch" ]; then
	if ! pacman -Qs wpa_supplicant >/dev/null 2>&1; then
		printf "$print_wpa"
		sudo pacman -S wpa_supplicant --noconfirm
	fi
	if ! pacman -Qs dhclient >/dev/null 2>&1; then
		printf "$print_dhcp"
		sudo pacman -S dhclient --noconfirm
	fi
elif [ "$OS" == "redhat" ] || [ "$OS" == "centos" ] || [ "$OS" == "fedora" ]; then
	if ! yum list installed wpa_supplicant >/dev/null 2>&1; then
		printf "$print_wpa"
		sudo yum install wpa_supplicant -y
	fi
	if ! yum list installed dhclient >/dev/null 2>&1; then
		printf "$print_dhcp"
		sudo yum install dhclient -y
	fi
elif [ "OS" == "opensuse" ]; then
	if ! zypper se wpa_supplicant >/dev/null 2>&1; then
		printf "$print_wpa"
		sudo zypper install wpa_supplicant -n
	fi
	if ! zypper se dhclient >/dev/null 2>&1; then
		printf "$print_dhcp"
		sudo zypper install dhclient -n
	fi
fi


# list_interfaces(){
	
# 	printf "List of available Network interfaces\n\n"
# 	count=0
# 	shopt -s nullglob
# 	arr=(/sys/class/net/*)
# 	interfaces=()
# 	for ((i=0; i<${#arr[@]}; i++)); do
# 		if ! [ "${arr[$i]}" == "/sys/class/net/lo" ]; then
# 			interfaces[$count]="${arr[$i]}"
# 			((count++))
# 		fi
# 	done
# 	for ((i=0;i<${#interfaces[@]}; i++)); do
# 		interfaces[$i]=$(cut -d'/' -f5 "${interfaces[$i]}")
# 		printf "${interfaces[$i]}\n"
# 		# echo "HEllo"
# 	done
# }

list_interfaces(){
	printf "List of available Wireless Network interfaces:\n"
	printf "$(iw dev | awk '$1=="Interface"{print $2}')\n"
	finished=false
	choice=""
	while [ "$finished" == "false" ]; do
		printf "[choice] Please Input name of interface you want to use : "
		read choice
		iw $choice info >/dev/null 2>&1
		estatus=$?
		if [ "$estatus" == "0" ]; then
			finished=true
		else
			printf "Mind your fingers.\n"
		fi
	done
	make_configuration $choice
}